version: '3'

services:
  node-app:
    build:
      context: .
      dockerfile: ./express/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./express:/app

  nginx:
    build:
      context: .
      dockerfile: ./www/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./www/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
